import { Card } from "@/components/ui/Card";
import type { Lesson } from "./api";

function fNum(val: number | null | undefined): string {
  if (val === null || val === undefined || !Number.isFinite(val)) return "—";
  return val.toLocaleString(undefined, { minimumFractionDigits: 1, maximumFractionDigits: 1 });
}

function Section({ title, items, toneCls }: { title: string; items: string[] | null; toneCls?: string }) {
  if (!items || items.length === 0) return null;
  return (
    <div>
      <h4 className="mb-2 text-xs font-semibold uppercase tracking-[0.1em] text-terminal-muted border-b border-terminal-border pb-1">
        {title}
      </h4>
      <ul className="space-y-1.5 pl-4 list-disc text-sm">
        {items.map((txt, i) => (
          <li key={i} className={toneCls || "text-terminal-text"}>{txt}</li>
        ))}
      </ul>
    </div>
  );
}

export function LessonCard({ lesson }: { lesson: Lesson }) {
  return (
    <Card>
      <div className="mb-4 flex flex-wrap items-center justify-between border-b border-terminal-border pb-3">
        <div>
          <h3 className="text-sm font-semibold text-terminal-text">
            Review: {lesson.period_start} to {lesson.period_end}
          </h3>
          <p className="mt-1 text-[11px] text-terminal-muted uppercase tracking-[0.1em]">
            Generated at {new Date(lesson.created_at).toLocaleString()}
          </p>
        </div>
        <div className="flex gap-4">
          <div>
            <p className="text-[10px] uppercase text-terminal-muted">Trades</p>
            <p className="mt-0.5 text-sm font-semibold tabular-nums text-terminal-text">{lesson.trade_count ?? "—"}</p>
          </div>
          <div>
            <p className="text-[10px] uppercase text-terminal-muted">Win Rate</p>
            <p className="mt-0.5 text-sm font-semibold tabular-nums text-terminal-cyan">{fNum(lesson.win_rate)}%</p>
          </div>
          <div>
            <p className="text-[10px] uppercase text-terminal-muted">Net R</p>
            <p className={`mt-0.5 text-sm font-semibold tabular-nums ${lesson.net_r && lesson.net_r >= 0 ? "text-terminal-green" : "text-terminal-red"}`}>
              {fNum(lesson.net_r)}R
            </p>
          </div>
        </div>
      </div>

      {lesson.summary ? (
        <p className="mb-6 text-sm italic leading-relaxed text-terminal-text/90 border-l-2 border-terminal-cyan/50 pl-3">
          "{lesson.summary}"
        </p>
      ) : null}

      <div className="grid gap-6 md:grid-cols-2">
        <Section title="Strengths" items={lesson.strengths} toneCls="text-terminal-green" />
        <Section title="Weaknesses" items={lesson.weaknesses} toneCls="text-terminal-red" />
        <Section title="Observed Patterns" items={lesson.patterns} />
        <Section title="Actionable Recommendations" items={lesson.recommendations} toneCls="text-terminal-cyan font-medium" />
      </div>

      {lesson.model_used ? (
        <p className="mt-6 text-right text-[10px] text-terminal-muted">
          Generated by {lesson.model_used}
        </p>
      ) : null}
    </Card>
  );
}
